import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/contexts/providers";
import localFont from "next/font/local";
import GoogleAnalytics from "@/components/google-analytics";

const myFont = localFont({
  src: [
    {
      path: "../public/assets/fonts/mazdatypeviet-regular.woff",
      weight: "400",
      style: "regular",
    },
    {
      path: "../public/assets/fonts/mazdatypeviet-medium.woff",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/assets/fonts/mazdatypeviet-bold.woff",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>

      <GoogleAnalytics />
    </html>
  );
}
